- name: 'apt | install dependencies'
  action: 'apt pkg={{ item }}'
  with_items:
    - 'build-essential'
    - 'libssl-dev'
    - 'libyaml-dev'
    - 'libreadline6-dev'
    - 'zlib1g-dev'
    - 'libcurl4-openssl-dev'
    - 'git'
    - 'nginx'
    - 'redis-server'
    - 'sphinxsearch'
    - 'exim4-daemon-light'
    - 'mailutils'
    - 'postgresql'
    - 'postgresql-contrib'
    - 'postgresql-server-dev-9.5'
    - 'monit'
    - 'libpq-dev'
    - 'imagemagick'
    - 'libmagickwand-dev'
    - 'nodejs'
    - 'zip'
    - 'unzip'
    - 'htop'
    - 'mc'